-- =============================================================
-- Schema PostgreSQL - ProjetoEM
-- Convertido a partir de MigradorBanco.cs (Firebird)
-- Banco novo/vazio: rode este script UMA VEZ no editor SQL do Neon.
-- =============================================================

-- ── Aluno ───────────────────────────────────────────────────
CREATE TABLE TBALUNO (
    ALUNMATRICULA INTEGER      NOT NULL,
    ALUNNOME      VARCHAR(150) NOT NULL,
    ALUNCPF       VARCHAR(14),
    ALUNDTNASC    INTEGER      NOT NULL,
    ALUNSEXO      INTEGER      NOT NULL,
    ALUNCIDADETXT VARCHAR(100),
    ALUNBAIRRO    VARCHAR(100),
    ALUNRESPNOME  VARCHAR(100),
    ALUNRESPTEL   VARCHAR(20),
    ALUNRESPPAR   VARCHAR(50),
    ALUNSTATUS    INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TBALUNO PRIMARY KEY (ALUNMATRICULA)
);
CREATE SEQUENCE GEN_TBALUNO;

-- ── Observações do aluno ───────────────────────────────────
CREATE TABLE TBOBSALUNO (
    OBSCODIGO INTEGER      NOT NULL,
    OBSALUNO  INTEGER      NOT NULL,
    OBSDATA   INTEGER      NOT NULL,
    OBSTEXTO  VARCHAR(200) NOT NULL,
    CONSTRAINT PK_TBOBSALUNO PRIMARY KEY (OBSCODIGO),
    CONSTRAINT FK_OBS_ALUNO FOREIGN KEY (OBSALUNO) REFERENCES TBALUNO (ALUNMATRICULA)
);
CREATE SEQUENCE GEN_TBOBSALUNO;

-- ── Histórico do aluno (linha do tempo) ────────────────────
CREATE TABLE TBHISTALUNO (
    HISCODIGO INTEGER      NOT NULL,
    HISALUNO  INTEGER      NOT NULL,
    HISDATA   INTEGER      NOT NULL,
    HISTEXTO  VARCHAR(200) NOT NULL,
    CONSTRAINT PK_TBHISTALUNO PRIMARY KEY (HISCODIGO),
    CONSTRAINT FK_HIS_ALUNO FOREIGN KEY (HISALUNO) REFERENCES TBALUNO (ALUNMATRICULA)
);
CREATE SEQUENCE GEN_TBHISTALUNO;

-- ── Turma ───────────────────────────────────────────────────
CREATE TABLE TBTURMA (
    TURMCODIGO    INTEGER      NOT NULL,
    TURMNOME      VARCHAR(100) NOT NULL,
    TURMAANO      INTEGER      NOT NULL,
    TURMPROFESSOR VARCHAR(100),
    TURMDIAS      VARCHAR(60),
    TURMHORARIO   VARCHAR(20),
    CONSTRAINT PK_TBTURMA PRIMARY KEY (TURMCODIGO)
);
CREATE SEQUENCE GEN_TBTURMA;

CREATE TABLE TBTURMA_ALUNO (
    TURMCODIGO    INTEGER NOT NULL,
    ALUNMATRICULA INTEGER NOT NULL,
    CONSTRAINT PK_TBTURMA_ALUNO PRIMARY KEY (TURMCODIGO, ALUNMATRICULA),
    CONSTRAINT FK_TA_TURMA FOREIGN KEY (TURMCODIGO)    REFERENCES TBTURMA (TURMCODIGO),
    CONSTRAINT FK_TA_ALUNO FOREIGN KEY (ALUNMATRICULA) REFERENCES TBALUNO (ALUNMATRICULA)
);

-- ── Encontros (frequência por turma) ───────────────────────
CREATE TABLE TBENCONTRO (
    ENCCODIGO INTEGER NOT NULL,
    ENCTURMA  INTEGER NOT NULL,
    ENCDATA   INTEGER NOT NULL,
    CONSTRAINT PK_TBENCONTRO PRIMARY KEY (ENCCODIGO),
    CONSTRAINT FK_ENC_TURMA FOREIGN KEY (ENCTURMA) REFERENCES TBTURMA (TURMCODIGO)
);
CREATE SEQUENCE GEN_TBENCONTRO;

CREATE TABLE TBENCPRESENCA (
    ENCCODIGO     INTEGER NOT NULL,
    ALUNMATRICULA INTEGER NOT NULL,
    PRESENTE      INTEGER NOT NULL,
    CONSTRAINT PK_TBENCPRESENCA PRIMARY KEY (ENCCODIGO, ALUNMATRICULA),
    CONSTRAINT FK_PRES_ENC   FOREIGN KEY (ENCCODIGO)     REFERENCES TBENCONTRO (ENCCODIGO),
    CONSTRAINT FK_PRES_ALUNO FOREIGN KEY (ALUNMATRICULA) REFERENCES TBALUNO (ALUNMATRICULA)
);

-- ── Eventos ─────────────────────────────────────────────────
CREATE TABLE TBEVENTO (
    EVECODIGO INTEGER      NOT NULL,
    EVENOME   VARCHAR(100) NOT NULL,
    EVEDATA   INTEGER      NOT NULL,
    EVEOBS    VARCHAR(200),
    CONSTRAINT PK_TBEVENTO PRIMARY KEY (EVECODIGO)
);
CREATE SEQUENCE GEN_TBEVENTO;

CREATE TABLE TBEVENTOALUNO (
    EVECODIGO     INTEGER NOT NULL,
    ALUNMATRICULA INTEGER NOT NULL,
    CONSTRAINT PK_TBEVENTOALUNO PRIMARY KEY (EVECODIGO, ALUNMATRICULA),
    CONSTRAINT FK_EVAL_EVENTO FOREIGN KEY (EVECODIGO)     REFERENCES TBEVENTO (EVECODIGO),
    CONSTRAINT FK_EVAL_ALUNO  FOREIGN KEY (ALUNMATRICULA) REFERENCES TBALUNO (ALUNMATRICULA)
);

-- ── Voluntários ─────────────────────────────────────────────
CREATE TABLE TBVOLUNTARIO (
    VOLCODIGO   INTEGER      NOT NULL,
    VOLNOME     VARCHAR(100) NOT NULL,
    VOLTELEFONE VARCHAR(20),
    VOLFUNCAO   VARCHAR(50),
    CONSTRAINT PK_TBVOLUNTARIO PRIMARY KEY (VOLCODIGO)
);
CREATE SEQUENCE GEN_TBVOLUNTARIO;

-- ── Doações ─────────────────────────────────────────────────
CREATE TABLE TBDOACAO (
    DOACODIGO INTEGER      NOT NULL,
    DOAITEM   VARCHAR(150) NOT NULL,
    DOAQTD    INTEGER,
    DOADATA   INTEGER      NOT NULL,
    DOADOADOR VARCHAR(100),
    CONSTRAINT PK_TBDOACAO PRIMARY KEY (DOACODIGO)
);
CREATE SEQUENCE GEN_TBDOACAO;

-- ── Usuários (autenticação) ─────────────────────────────────
CREATE TABLE TBUSUARIO (
    USUCODIGO INTEGER      NOT NULL,
    USULOGIN  VARCHAR(50)  NOT NULL,
    USUNOME   VARCHAR(100) NOT NULL,
    USUHASH   VARCHAR(300) NOT NULL,
    CONSTRAINT PK_TBUSUARIO PRIMARY KEY (USUCODIGO),
    CONSTRAINT UQ_TBUSUARIO_LOGIN UNIQUE (USULOGIN)
);
CREATE SEQUENCE GEN_TBUSUARIO;
