-- =============================================================
-- Migração: adiciona tabelas TBTURMA e TBTURMA_ALUNO
-- =============================================================

CREATE TABLE TBTURMA (
    TURMCODIGO INTEGER      NOT NULL,
    TURMNOME   VARCHAR(100) NOT NULL,
    TURMAANO   INTEGER      NOT NULL,
    CONSTRAINT PK_TBTURMA PRIMARY KEY (TURMCODIGO)
);

CREATE SEQUENCE GEN_TBTURMA;
ALTER SEQUENCE GEN_TBTURMA RESTART WITH 1;

CREATE TABLE TBTURMA_ALUNO (
    TURMCODIGO    INTEGER NOT NULL,
    ALUNMATRICULA INTEGER NOT NULL,
    CONSTRAINT PK_TBTURMA_ALUNO  PRIMARY KEY (TURMCODIGO, ALUNMATRICULA),
    CONSTRAINT FK_TA_TURMA FOREIGN KEY (TURMCODIGO)    REFERENCES TBTURMA (TURMCODIGO),
    CONSTRAINT FK_TA_ALUNO FOREIGN KEY (ALUNMATRICULA) REFERENCES TBALUNO (ALUNMATRICULA)
);

COMMIT;
